import { WatchOrderEntry } from '@/types'

export interface CalendarConfig {
  startDate: string      // 'YYYY-MM-DD'
  episodesPerDay: number // >= 1
  watchStartTime: string // 'HH:MM'
}

const CRLF = '\r\n'

function formatUTC(d: Date): string {
  // YYYYMMDDTHHMMSSZ — RFC 5545 UTC form
  return d.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'
}

function foldLine(line: string): string {
  if (line.length <= 75) return line
  const chunks: string[] = []
  let i = 0
  while (i < line.length) {
    chunks.push(line.slice(i, i + 73))
    i += 73
  }
  return chunks.join(CRLF + ' ')
}

function escapeIcsText(s: string): string {
  // RFC 5545 §3.3.11: escape commas, semicolons, backslashes, and newlines
  return s
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\n/g, '\\n')
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 40) || 'franchise'
}

/**
 * Build a spec-compliant iCalendar (.ics) feed scheduling each episode
 * sequentially at the user's pace.
 */
export function generateWatchCalendarIcs(
  franchiseName: string,
  entries: WatchOrderEntry[],
  config: CalendarConfig,
): string {
  if (!entries?.length) {
    throw new Error('generateWatchCalendarIcs: entries is empty')
  }
  
  // Defensive guard against 0 or negative episodes pace
  const pace = Math.max(1, Number.isFinite(config.episodesPerDay) ? config.episodesPerDay : 2)

  const [sy, sm, sd] = config.startDate.split('-').map(Number)
  const [hh, mm] = config.watchStartTime.split(':').map(Number)
  if ([sy, sm, sd, hh, mm].some(n => !Number.isFinite(n))) {
    throw new Error('generateWatchCalendarIcs: invalid startDate or watchStartTime')
  }

  const startOfDay = new Date(sy, sm - 1, sd, hh, mm, 0, 0)
  const stamp = formatUTC(new Date()) // Fix: Generate DTSTAMP once outside the loop
  const slug = slugify(franchiseName)

  const lines: string[] = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//ChronoFlow//Anime Watch Schedule//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${escapeIcsText(franchiseName)} watch plan`,
    `X-WR-CALDESC:${escapeIcsText(`Daily watch schedule for ${franchiseName} generated by ChronoFlow`)}`,
  ]

  // Flatten to per-episode queue
  const queue: { title: string; seriesTitle: string; duration: number }[] = []
  for (const entry of entries) {
    const epCount = Math.max(1, entry.episodeCount ?? 1)
    const duration = Math.max(1, entry.durationMinutes ?? 24)
    for (let i = 1; i <= epCount; i++) {
      queue.push({
        title: epCount === 1 ? entry.title : `${entry.title} — Episode ${i}`,
        seriesTitle: entry.title,
        duration,
      })
    }
  }

  let dayCursor = new Date(startOfDay.getTime())
  let scheduledToday = 0

  queue.forEach((ep, index) => {
    if (scheduledToday >= pace) {
      // Advance to next day, reset to user's preferred watch hour
      dayCursor = new Date(dayCursor.getTime())
      dayCursor.setDate(dayCursor.getDate() + 1)
      dayCursor.setHours(hh, mm, 0, 0)
      scheduledToday = 0
    }

    const eventStart = new Date(dayCursor.getTime())
    const eventEnd = new Date(eventStart.getTime() + ep.duration * 60_000)

    const summary = `Watch: ${ep.title}`
    const description = [
      'Time to watch your scheduled episode!',
      '',
      `Series: ${ep.seriesTitle}`,
      `Duration: ${ep.duration} minutes`,
      '',
      'Watch plan generated via ChronoFlow.',
    ].join('\n')

    lines.push('BEGIN:VEVENT')
    // Fix: Deterministic UIDs so calendar updates sync smoothly on subsequent imports
    lines.push(foldLine(`UID:${slug}-ep-${String(index).padStart(5, '0')}@chronoflow.app`))
    lines.push(`DTSTAMP:${stamp}`)
    lines.push(`DTSTART:${formatUTC(eventStart)}`)
    lines.push(`DTEND:${formatUTC(eventEnd)}`)
    lines.push(foldLine(`SUMMARY:${escapeIcsText(summary)}`))
    lines.push(foldLine(`DESCRIPTION:${escapeIcsText(description)}`))
    lines.push('END:VEVENT')

    // Advance same-day cursor: end of current episode + 5 min buffer
    dayCursor = new Date(eventEnd.getTime() + 5 * 60_000)
    scheduledToday++
  })

  lines.push('END:VCALENDAR')
  return lines.join(CRLF) + CRLF
}

/**
 * Trigger a browser download of the .ics content.
 */
export function downloadIcsFile(filename: string, content: string): void {
  if (typeof window === 'undefined') return
  const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  // Revoke after a tick so download can start safely
  setTimeout(() => URL.revokeObjectURL(url), 0)
}
