import { WatchOrderEntry } from '@/types';
import { CustomSchedule } from '@/types';

export interface CalendarConfig {
  startDate: string;      // 'YYYY-MM-DD'
  episodesPerDay: number; // >= 1
  watchStartTime: string; // 'HH:MM'
  customSchedule?: CustomSchedule; // Added support
}

const CRLF = '\r\n';

function formatUTC(d: Date): string {
  // YYYYMMDDTHHMMSSZ — RFC 5545 UTC form
  return d.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
}

function foldLine(line: string): string {
  if (line.length <= 75) return line;
  const chunks: string[] = [];
  let i = 0;
  while (i < line.length) {
    chunks.push(line.slice(i, i + 73));
    i += 73;
  }
  return chunks.join(CRLF + ' ');
}

function escapeIcsText(s: string): string {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\n/g, '\\n');
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 40) || 'franchise';
}

export function generateWatchCalendarIcs(
  franchiseName: string,
  entries: WatchOrderEntry[],
  config: CalendarConfig,
): string {
  if (!entries?.length) {
    throw new Error('generateWatchCalendarIcs: entries is empty');
  }

  const pace = Math.max(1, Number.isFinite(config.episodesPerDay) ? config.episodesPerDay : 2);

  const [sy, sm, sd] = config.startDate.split('-').map(Number);
  const [hh, mm] = config.watchStartTime.split(':').map(Number);
  if ([sy, sm, sd, hh, mm].some(n => !Number.isFinite(n))) {
    throw new Error('generateWatchCalendarIcs: invalid startDate or watchStartTime');
  }

  const startOfDay = new Date(sy, sm - 1, sd, hh, mm, 0, 0);
  const stamp = formatUTC(new Date());
  const slug = slugify(franchiseName);

  const lines: string[] = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//ChronoFlow//Anime Watch Schedule//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${escapeIcsText(franchiseName)} watch plan`,
    `X-WR-CALDESC:${escapeIcsText(`Daily watch schedule for ${franchiseName} generated by ChronoFlow`)}`,
  ];

  const queue: { title: string; seriesTitle: string; duration: number }[] = [];
  for (const entry of entries) {
    const epCount = Math.max(1, entry.episodeCount ?? 1);
    const duration = Math.max(1, entry.durationMinutes ?? 24);
    for (let i = 1; i <= epCount; i++) {
      queue.push({
        title: epCount === 1 ? entry.title : `${entry.title} — Episode ${i}`,
        seriesTitle: entry.title,
        duration,
      });
    }
  }

  let dayCursor = new Date(startOfDay.getTime());
  const daysOfWeek = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"] as const;

  if (config.customSchedule?.enabled) {
    const sched = config.customSchedule;
    let eventCount = 0;

    queue.forEach((ep) => {
      let foundSlot = false;
      while (!foundSlot) {
        const dayName = daysOfWeek[dayCursor.getDay()];
        const daily = sched[dayName];

        if (daily && daily.enabled) {
          const [startH, startM] = daily.startTime.split(":").map(Number);
          const [endH, endM] = daily.endTime.split(":").map(Number);

          const windowStart = new Date(dayCursor.getTime());
          windowStart.setHours(startH, startM, 0, 0);

          const windowEnd = new Date(dayCursor.getTime());
          windowEnd.setHours(endH, endM, 0, 0);

          if (dayCursor.getTime() < windowStart.getTime()) {
            dayCursor.setTime(windowStart.getTime());
          }

          const eventEnd = new Date(dayCursor.getTime() + ep.duration * 60_000);
          if (eventEnd.getTime() <= windowEnd.getTime()) {
            const eventStart = new Date(dayCursor.getTime());

            const summary = `Watch: ${ep.title}`;
            const description = [
              'Time to watch your scheduled episode!',
              '',
              `Series: ${ep.seriesTitle}`,
              `Duration: ${ep.duration} minutes`,
              '',
              'Watch plan generated via ChronoFlow.',
            ].join('\n');

            lines.push('BEGIN:VEVENT');
            lines.push(foldLine(`UID:${slug}-ep-${String(eventCount).padStart(5, '0')}@chronoflow.app`));
            lines.push(`DTSTAMP:${stamp}`);
            lines.push(`DTSTART:${formatUTC(eventStart)}`);
            lines.push(`DTEND:${formatUTC(eventEnd)}`);
            lines.push(foldLine(`SUMMARY:${escapeIcsText(summary)}`));
            lines.push(foldLine(`DESCRIPTION:${escapeIcsText(description)}`));
            lines.push('END:VEVENT');

            dayCursor = new Date(eventEnd.getTime() + 5 * 60_000);
            eventCount++;
            foundSlot = true;
          } else {
            dayCursor.setDate(dayCursor.getDate() + 1);
            dayCursor.setHours(0, 0, 0, 0);
          }
        } else {
          dayCursor.setDate(dayCursor.getDate() + 1);
          dayCursor.setHours(0, 0, 0, 0);
        }
      }
    });
  } else {
    // Legacy Uniform episodesPerDay schedule
    let scheduledToday = 0;
    queue.forEach((ep, index) => {
      if (scheduledToday >= pace) {
        dayCursor = new Date(dayCursor.getTime());
        dayCursor.setDate(dayCursor.getDate() + 1);
        dayCursor.setHours(hh, mm, 0, 0);
        scheduledToday = 0;
      }

      const eventStart = new Date(dayCursor.getTime());
      const eventEnd = new Date(eventStart.getTime() + ep.duration * 60_000);

      const summary = `Watch: ${ep.title}`;
      const description = [
        'Time to watch your scheduled episode!',
        '',
        `Series: ${ep.seriesTitle}`,
        `Duration: ${ep.duration} minutes`,
        '',
        'Watch plan generated via ChronoFlow.',
      ].join('\n');

      lines.push('BEGIN:VEVENT');
      lines.push(foldLine(`UID:${slug}-ep-${String(index).padStart(5, '0')}@chronoflow.app`));
      lines.push(`DTSTAMP:${stamp}`);
      lines.push(`DTSTART:${formatUTC(eventStart)}`);
      lines.push(`DTEND:${formatUTC(eventEnd)}`);
      lines.push(foldLine(`SUMMARY:${escapeIcsText(summary)}`));
      lines.push(foldLine(`DESCRIPTION:${escapeIcsText(description)}`));
      lines.push('END:VEVENT');

      dayCursor = new Date(eventEnd.getTime() + 5 * 60_000);
      scheduledToday++;
    });
  }

  lines.push('END:VCALENDAR');
  return lines.join(CRLF) + CRLF;
}

export function downloadIcsFile(filename: string, content: string): void {
  if (typeof window === 'undefined') return;
  const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 0);
}
